name: Publish docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.11

jobs:
  publish-pages:
    name: Publish Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./docs

      - name: Publish Docs
        run: mkdocs gh-deploy --force
        working-directory: ./docs