name: Unit tests

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run test:unit
